### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #127: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #127

### CODE REVIEW

**Review by demurgos — APPROVED** [review]

**Comment by TheDancingCode** [comment]
@schickling 
Did you get a chance to look at this?

**Comment by TheDancingCode** [comment]
Another friendly reminder.

**Comment by schickling** [comment]
Sorry for the delay. Just added you as a collaborator. Please tell me your NPM handle, so I can add you there as well so you can publish new versions.

**Comment by TheDancingCode** [comment]
Thank you for the invitation, but this pull request was more like a one-off contribution. I performed a lot of these pull requests for different gulp plugins, also for plugins I don't use myself, like this one. I wouldn't be of much help as a collaborator on this project. Are you no longer maintaining it?

**Comment by schickling** [comment]
Unfortunately I don't have the time these days anymore. Happy to add a new collaborator if someone is up for it! 🙌

**Pull request closed without merging**
