### PR TITLE
Suport gzip and deflate encoding 

### PR DESCRIPTION
**Pull request by hypnoce**
Hello,

we are using gulp-webserver with great success in my company.
Nevertheless, we needed support for gzip and deflate compression.
Is it a feature you would like to support ?

Thanks

### CODE REVIEW

**Comment by MartinMoizard** [comment]
+1

**Comment by hypnoce** [comment]
Hi,

any news on this pull request ?

thanks

**Comment by hypnoce** [comment]
Hi, are you considering pull requests on this repo ?

**Comment by alwayrun** [comment]
+1

**Pull request closed without merging**
